version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "release/1.1.0"
    schedule:
      interval: "weekly"
    groups:
      npm_and_yarn:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
